# Generated by Django 4.2 on 2026-04-17 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0008_lpgusage_liters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(default='tablet', max_length=20)),
                ('dosage_per_intake', models.DecimalField(decimal_places=2, max_digits=6)),
                ('intakes_per_day', models.PositiveIntegerField(default=1)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('tablets', 'Tablets'), ('ml', 'ml'), ('units', 'Units')], default='tablets', max_length=20)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['medicine_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='advance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='lpgusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('add', 'Add'), ('consume', 'Consume'), ('adjust', 'Adjust')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='purchase.medicine')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
