# Generated by Django 4.2 on 2026-04-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0009_medicine_alter_advance_options_alter_lpgusage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('mom', 'Mom'), ('dad', 'Dad'), ('son', 'Son'), ('daughter', 'Daughter'), ('other', 'Other')], default='other', max_length=20)),
                ('treatment_type', models.CharField(choices=[('allopathic', 'Allopathic'), ('ayurvedic', 'Ayurvedic'), ('homeopathic', 'Homeopathic'), ('other', 'Other')], default='allopathic', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='purchase.patient'),
        ),
    ]
