# Generated by Django 4.2 on 2026-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_patient_medicine_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='food_relation',
            field=models.CharField(blank=True, choices=[('before_food', 'Before Food'), ('after_food', 'After Food'), ('with_food', 'With Food'), ('no_restriction', 'No Restriction')], default='no_restriction', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='timing',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('as_needed', 'As Needed')], default='morning', max_length=20),
        ),
    ]
