# Generated by Django 4.2 on 2026-04-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_medicine_food_relation_medicine_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='afternoon_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='evening_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='morning_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='night_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_per_intake',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('tablets', 'Tablets'), ('mg', 'mg'), ('ml', 'ml'), ('units', 'Units')], default='tablets', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='type',
            field=models.CharField(choices=[('add', 'Add'), ('consume', 'Consume'), ('adjust', 'Adjust'), ('discard', 'Discard')], max_length=10),
        ),
    ]
