# Generated by Django 4.2 on 2026-04-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_medicine_afternoon_dose_medicine_evening_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='', max_length=10),
        ),
    ]
