# Generated by Django 4.2 on 2026-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_medicine_purchases_consulting_vitals_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='prescribed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
