# Generated by Django 4.2 on 2026-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_medicine_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthexpense',
            name='paid_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
