# Generated by Django 4.2 on 2026-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_reminder_skip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
