# Generated by Django 4.2 on 2026-05-30 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0020_journal_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HomeSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('store_name', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spends', to='purchase.spendcategory')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_spends', to='purchase.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_spends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('entertainment', 'Entertainment'), ('climate', 'Air/Climate'), ('computing', 'Computing'), ('mobile', 'Mobile/Phone'), ('lighting', 'Lighting'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('amc_expiry', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_appliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('units_consumed', models.FloatField()),
                ('amount', models.FloatField()),
                ('opening_reading', models.FloatField(blank=True, null=True)),
                ('closing_reading', models.FloatField(blank=True, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='EducationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('tuition', 'Tuition/School Fee'), ('transport', 'Transport'), ('food', 'Food/Tiffin'), ('books', 'Books/Stationery'), ('uniform', 'Uniform/Shoes'), ('activity', 'Activity/Sports'), ('exam', 'Exam/Test Fee'), ('coaching', 'Coaching/Tuition Class'), ('other', 'Other')], default='tuition', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_expenses', to='purchase.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplianceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_type', models.CharField(choices=[('routine', 'Routine'), ('repair', 'Repair'), ('amc', 'AMC Service'), ('installation', 'Installation'), ('other', 'Other')], default='routine', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('cost', models.FloatField(default=0)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('bill_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='purchase.homeappliance')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
