# Generated by Django 4.2 on 2026-06-02 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0021_home_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('self', 'Self/Me'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='PaybackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paybacks', to='purchase.lendinglog')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='lendinglog',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lendings', to='purchase.familymember'),
        ),
        migrations.AddField(
            model_name='lendinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to=settings.AUTH_USER_MODEL),
        ),
    ]
